<section id="cta_noticias">
    <header>
        <form name="buscador">
            <label for="titulo">
                Titulo
            </label>
            <input id="titulo" name="titulo" type="text">
            <label for="fecha">
                Fecha
            </label>
            <input id="fecha" name="fecha" type="date">
            <button><?= __('Buscar') ?></button>
        </form>
    </header>

    <?php foreach ($this->getNoticiasCollection() as $article): ?>
        <article>
            <figure>
                <img src="">
            </figure>
            <header>
                <h2>Titulo</h2>
                <time>Fecha Publicacion</time>
            </header>
            aklajslkajlask
            <footer>
                <a href="#">Leer más</a>
            </footer>
        </article>
        <hr>
    <?php endforeach; ?>

    <footer>
        <div id ="paginacion">
            <div><?=$this->getPagerHtml()?></div>
        </div>
    </footer>
</section>
