<section id="cta_noticias">
    <header>
        <form name="buscador">
            <label for="titulo">
                <?= __('Titulo') ?>
            </label>
            <input id="titulo" name="titulo" type="text">
            <label for="fecha">
                <?= __('Fecha') ?>
            </label>
            <input id="fecha" name="fecha" type="date">
            <button><?= __('Buscar') ?></button>
        </form>
    </header>

    <?php if ($this->getNoticiasCollection()->count() === 0): ?>
        <p class="empty-articles-message"><?= __('No hay artículos') ?></p>
    <?php endif; ?>
    <?php foreach ($this->getNoticiasCollection() as $article): ?>
        <article>
            <figure>
                <img src="">
            </figure>
            <header>
                <h2><?= $article['titulo'] ?></h2>
                <time><?= __('Fecha Publicacion') ?>: <?= $article['fechaPublicacion'] ?></time>
            </header>
            <i>content...</i>
            <footer>
                <a href="#"><?= __('Leer más') ?></a>
            </footer>
        </article>
        <hr>
    <?php endforeach; ?>

    <footer>
        <div id ="paginacion">
            <div><?= $this->getPagerHtml() ?></div>
        </div>
    </footer>
</section>
