<div id="test-div" data-bind="scope: 'test'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#test-div": {
                "Magento_Ui/js/core/app": "<?php /* @escapeNotVerified */ echo $this->getJsLayout() ?>"
            }
        }
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function (url, blockLoader) {
            blockLoader('<?php /* @escapeNotVerified */ echo $this->getViewFileUrl('images/loader-1.gif') ?>');
            return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $this->getBaseUrl() ?>');
        });
    </script>
</div>
